src/main/java/com/yutgame/Main.java
player의 수를 2명에서 4명, piece의  수를 2개에서 5개로 설정할 수 있도록 함. board의 모양은 이후 오각형, 육각형 보드 클래스를 구현한 뒤 수정 예정
=> feat : main에서 player, piece의 수, board 모양 설정하는 로직 추가

src/main/java/com/yutgame/model/Piece.java
Piece 클래스의 주석 정리, currentNode 초기화 추가
=> refactor : Piece 클래스의 주석 정리, currentNode 초기화 추가

.idea/misc.xml, src/main/java/com/yutgame/view/swing/SwingYutGameView.java
=> fix#9 : 시작 시 화면 크기 조정

src/main/java/com/yutgame/Main.java, src/main/java/com/yutgame/model/Player.java, src/main/java/com/yutgame/model/YutGame.java, src/main/java/com/yutgame/view/swing/SwingYutGameView.java
- 팝업창에서 플레이어수를 선택할 수 있도록 수정했습니다.
-
=> Fix/#11: 팝업창 UI/UX 개선

.idea/misc.xml, src/main/java/com/yutgame/model/YutGame.java
- 기존에는 말을 업었을 때 말이 한 번에 이동하지 않는 문제가 있었음
- 이 말들이 함께 움직일 수 있도록 수정
=> fix #6 : 그룹된 말이 한 번에 이동할 수 있도록 수정

src/main/java/com/yutgame/view/swing/SwingYutGameView.java
- processAllThrows() 재투척 조건을 YUT/MO 결과로 한정
- game.hasExtraTurnFlag() 호출 및 잡기 추가턴 누적 제거
- javadoc 및 변수명 간결화로 가독성 향상
=> refactor : 연속 던지기 로직 단순화

src/main/java/com/yutgame/model/YutGame.java
- 윷놀이 실제 확률을 반영하여 각 결과가 나올 확률을 조정하였습니다.
=> fix #8: 실제 윷놀이 확률 반영

src/main/java/com/yutgame/model/YutGame.java, src/main/java/com/yutgame/view/swing/SwingYutGameView.java
=> fix #7: 윷, 모가 나왔을 때 연속 던지기 구현 중

src/main/java/com/yutgame/view/swing/SwingYutGameView.java
다이얼로그 X 버튼 클릭 시 윷 던지기 취소 처리 기능 추가
=> Fix/#24 다이얼로그 X 버튼 클릭 시 윷 던지기 취소 처리 기능 추가

src/main/java/com/yutgame/model/YutGame.java, src/main/java/com/yutgame/view/swing/BoardPanel.java, src/main/java/com/yutgame/view/swing/SwingYutGameView.java
- 맨 처음에 빽도가 나오면 반영하지 않고 다음 턴으로 넘어가도록 반영
- 빽도가 나왔을 때 미출발 말은 선택지에 없도록 수정
=> Fix/#26: 맨처음 빽도 반영 문제 + 빽도 말 선택 문제

src/main/java/com/yutgame/Main.java, src/main/java/com/yutgame/view/swing/SwingYutGameView.java
게임 세팅 로직을 SwingYutGameView로 이관하여 책임 분리 (Code Refactor)
=> refactor#36 : 게임 세팅 로직을 SwingYutGameView로 이관하여 책임 분리

src/main/java/com/yutgame/model/SquareBoard.java, src/main/java/com/yutgame/model/YutBoard.java, src/main/java/com/yutgame/model/YutGame.java, src/main/java/com/yutgame/view/swing/SwingYutGameView.java
start node 이상의 step을 갈 때도 완주 처리가 되도록 수정
=> fix #13 : start node 이상 갈 때 도착 처리

src/main/java/com/yutgame/model/Piece.java, src/main/java/com/yutgame/model/YutGame.java
=> fix #43 : 말 업은 상태로 완주 시 그룹핑된 말 모두 완주 처리

src/main/java/com/yutgame/view/swing/SwingYutGameView.java
=> fix #13 : 완주한 말은 이후의 말 선택지에서 제외되도록 수정

src/main/java/com/yutgame/model/HexagonBoard.java
아직 로직은 구현 전 (그래프 모양만 그려 둠 -> 육각형은 아직 돌리면 오류 나요!!)
+ 시작할 때 윷놀이 판 모양 선택하도록
=> feat #41: 육각형 그래프 그리기

src/main/java/com/yutgame/model/HexagonBoard.java
=> feat #41: 일단 작동이 되게

src/main/java/com/yutgame/model/HexagonBoard.java, src/main/java/com/yutgame/view/swing/SwingYutGameView.java
센터에 멈추고 출발하는 경우, a1 방향으로 이동
센터에 멈추지 않고 그냥 지름길 스쳐 지나가는거라면 f1 방향으로 이동!
=> 육각형 로직 (완주 처리 전까지) 구현 완료

src/main/java/com/yutgame/model/HexagonBoard.java, src/main/java/com/yutgame/model/PentagonBoard.java, src/main/java/com/yutgame/model/SquareBoard.java, src/main/java/com/yutgame/view/swing/SwingYutGameView.java
오각형 보드 구현 및 사각형 육각형 꼭짓점 노드 이름 변경하여 isCrossroad() 통합
=> Pentagon implement (square, hexagon node's name change)

src/main/java/com/yutgame/view/swing/SwingYutGameView.java
=> fix #66 : 중간에 X를 눌렀을 때 오류가 발생하는 문제 해결

src/main/java/com/yutgame/model/PentagonBoard.java
=> fix #64 : 오각형 센터 갈림길 선택 없이 고정

src/main/java/com/yutgame/view/swing/SwingYutGameView.java
갈림길에서 완주 처리 시 완주 가능한 선택지를 Finish로 변경
=> fix #67: 갈림길에서 완주 처리 시 완주 가능한 선택지를 Finish로 변경

src/main/java/com/yutgame/view/swing/SwingYutGameView.java
=> 시작 설정 UI 예쁘게 만들기

src/main/java/com/yutgame/view/swing/SwingYutGameView.java
=> feat #76: 게임이 종료되면 화면 창도 같이 닫히게 수정

src/main/java/com/yutgame/view/swing/BoardPanel.java
플레이어가 바뀔 때마다 플레이어의 말 색깔로 배경색이 바뀌도록 변경
=> feat #80: 플레이어가 바뀔 때마다 플레이어의 말 색깔로 배경색이 바뀌도록 변경

src/main/java/com/yutgame/model/YutGame.java, src/main/java/com/yutgame/view/swing/SwingYutGameView.java
=> fix#31 : 시작노드에서 빽도 처리 못하도록 수정

src/main/java/com/yutgame/view/swing/SwingYutGameView.java
=> fix #96: 업은 말은 하나로 표시하도록 수정
